spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SzymonKuhn/configuration.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/